### ISSUE TITLE
ssh连接错误

### ISSUE THREAD

**Issue by xiaohuizhang** [liupzmin/weewoe#4]
操作系统：mint (Linux version 5.4.0-91-generic (buildd@lcy01-amd64-017) (gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)))
服务器无密码登录已完成，但是会提示没有配置的主机，查看know_host中不显示IP
ssh_config 中将HashKnownHosts 改为no，将know_host清空，重新做无密码登录，就会正常

             
![bug](https://user-images.githubusercontent.com/2887968/168943263-a886d944-d9e4-4c9c-b566-9d17ce55f8ba.png)

**Comment by liupzmin** [comment]
[SSH HashKnownHosts File Format](https://www.fragmentationneeded.net/2017/10/ssh-hashknownhosts-file-format.html) 解释了文件格式以及散列的方法，我们可以利用相同的方法计算出散列值，之后再和文件中的值比较

**Comment by liupzmin** [comment]
@xiaohuizhang  [commit](https://github.com/liupzmin/weewoe/commit/2713a7d5dab8f7d56138f5ab6146054f35f7e2c6) 已发布 v0.0.2 请再测试一下
